---

- name: "Provision a Docker Swarm cluster"
  hosts: all
  become: true
  vars_files:
    - defaults/main.yml
    - vars/main.yml
    - vars/Debian.yml
  pre_tasks:
    - raw: sudo apt install -y python-minimal
  tasks:
    - include: tasks/main.yml